set -g base-index 1
set -sg escape-time 1
setw -g pane-base-index 1
setw -g mode-keys vi

set -g prefix C-a
unbind C-b

bind C-a send-prefix

bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

bind x kill-session

set -g default-shell /usr/bin/fish
